### ISSUE TITLE
Post stylistic design

### ISSUE THREAD

**Issue by uPagge** [godofredoninja/simply#103]
Hey
Tell me how to make the same post design as in the photo. I'm not talking about the theme of the post, but about the stylistic design of the text: highlighting, colored frames, a large letter at the beginning of the paragraph.

![изображение](https://user-images.githubusercontent.com/40397740/133670593-0766c2e1-ebe4-4527-aed4-0bad997dd67e.png)

**Comment by godofredoninja** [comment]
Hi @uPagge 

I have not added to Simply's documentation, because I already knew that the[ ghost cards](https://ghost.org/changelog/cardmas/) were coming.

## First letter big
Add this in a markdown block and then create a [snippets](https://ghost.org/changelog/content-snippets/)

```hbs
<p class="has-first-letter">
    Hello my first legra is big 
</p>
```

![image](https://user-images.githubusercontent.com/10253167/147691974-357bc701-a243-4f33-a35a-46b42bfad9a2.png)

![image](https://user-images.githubusercontent.com/10253167/147692149-478e1f05-6060-4365-88c1-a22235bc9e13.png)


![image](https://user-images.githubusercontent.com/10253167/147691870-1d71adf7-cdaf-45b6-91b7-1a37a7282a77.png)
