### ISSUE TITLE
New pages

### ISSUE THREAD

**Issue by DamienPirsy** [godofredoninja/simply#27]
Hi, I'm using your awesome theme and I'd like to add pages to my blog.  Are you using some CSS framework? Is there a complete grid system and so on I can refer to?
Thank you

**Comment by godofredoninja** [comment]
I do not use framework. I use my own grid system

## 12 Columns

Our standard grid has 12 columns. No matter the size of the browser, each of these columns will always have an equal width.

```html
 <div class="row">
      <div class="col s1">1</div>
      <div class="col s1">2</div>
      <div class="col s1">3</div>
      <div class="col s1">4</div>
      <div class="col s1">5</div>
      <div class="col s1">6</div>
      <div class="col s1">7</div>
      <div class="col s1">8</div>
      <div class="col s1">9</div>
      <div class="col s1">10</div>
      <div class="col s1">11</div>
      <div class="col s1">12</div>
    </div>
```

## Adding Responsiveness

In the previous examples, we only defined the size for small screens using `col s12`. This is fine if we want a fixed layout since the rules propagate upwards. By just saying s12, we are essentially saying `col s12 m12 l12`. But by explicitly defining the size we can make our website more responsive.

```html
<div class="row">
    <div class="col s12"><p>s12</p></div>
    <div class="col s12 m4 l2"><p>s12 m4</p></div>
    <div class="col s12 m4 l8"><p>s12 m4</p></div>
    <div class="col s12 m4 l2"><p>s12 m4</p></div>
  </div>
```
