### ISSUE TITLE
Prismjs code highlight not working after using new update

### ISSUE THREAD

**Issue by ivanrodjr** [godofredoninja/simply#39]
*Summary*

Prismjs code highlight not working after using new update

Icons tested: Github, twitter, linkedIn

*Steps to reproduce*
- Activate new version on theme

*Actual Results*
- code highlight stops working, its displayed as regular section

*Expected Results*
- Highlights are working correctly

*Workaround*
- Use previous version

- Version 0.2.7
- Chrome 77, Mac Catalina
- Ghost 3
![image](https://user-images.githubusercontent.com/22507394/70462024-64faeb00-1a90-11ea-9c2c-5cb55eb8e249.png)

![image](https://user-images.githubusercontent.com/22507394/70462036-6af0cc00-1a90-11ea-8f0c-79b5d50afed9.png)

**Comment by godofredoninja** [comment]
My dear friend.

As I answered before. #38 

The problem is the CACHE. clear the cache or otherwise restart Ghost. `ghost restart`

Leave me the URL of your page to check.

Regards.

**Comment by ivanrodjr** [comment]
Already cleared the cache and restarted ghost. Site is hoolitest.com

**Comment by godofredoninja** [comment]
:thinking: The icons are not displayed because you delete the icon.

https://github.com/godofredoninja/simply/blob/92b668624ad1c15aaefe818b83208e83e1c8f576/default.hbs#L86

:arrow_right:  If you delete all of this. the theme won't work well. 

https://github.com/godofredoninja/simply/blob/92b668624ad1c15aaefe818b83208e83e1c8f576/default.hbs#L88-L132

**Comment by ivanrodjr** [comment]
Hey buddy, thats straight from your master zip, I just downloded and installed, I have not pulled or merged your code yet.
