### ISSUE TITLE
How to disable automatic dark theme 

### ISSUE THREAD

**Issue by hexclann** [godofredoninja/simply#88]
I don't want to use dark theme on my site, is it possible to completely disable it?

**Comment by godofredoninja** [comment]
Hi

Replace all the code with this one here

https://github.com/godofredoninja/simply/blob/bd4e94e56bb42c535e146bcdcea0478603512145/default.hbs#L23-L29

```html
<script>
        if (localStorage.theme === 'dark') {
            document.querySelector('html').classList.add('dark');
        } else {
            document.querySelector('html').classList.remove('light');
        }
    </script>
```

**Comment by hexclann** [comment]
Thanks for the reply, can I open a PR to add these info and changing font style from https://github.com/godofredoninja/simply/issues/59 to Docs?

**Comment by godofredoninja** [comment]
But I think you will need to make some updates because I changed some classes.

https://github.com/godofredoninja/simply/blob/bd4e94e56bb42c535e146bcdcea0478603512145/default.hbs#L32-L33

```html
<style>
    /* Global Typography and Titles */
    html, .font-sans, .button, .kg-bookmark-container, cite, figcaption, h1, h2, h3, h4, h5, h6, table {
        font-family: add_here_your_font;
    }
</style>

<style>
    /* Typography for post content */
    .font-serif .post-body, .spc-des {
        font-family: add_here_your_font;
    }
</style>
```

Of course you can add to the documentation. I will be happy for your collaboration.

https://github.com/godofredoninja/simply/blob/master/docs/settings.md
