### ISSUE TITLE
Recommended way to place Ads

### ISSUE THREAD

**Issue by yogeshbeniwal** [godofredoninja/simply#92]
Hello, 

There used to be partials for ad on at least 0.2.6 branch https://github.com/godofredoninja/simply/tree/0.2.6/partials/ad/. This seems to be removed from the latest version.

May i know what is the recommended way to insert ad now.

**Comment by godofredoninja** [comment]
Hi @yogeshbeniwal 

I have removed it because not everyone has been using it. Now most are using the members.

What I am thinking for the next versions is. If you are a member then the ads are removed and if you are not a member then the ads will be shown. 

For now, you can guide from previous version and add your ads.

**Comment by yogeshbeniwal** [comment]
That's very right approach, Ads and membership generally doesn't go well together. I have few other suggestions to improve this theme. Will create another thread for that and hopefully it will add some value.
