### ISSUE TITLE
Post excerpts not displaying correctly

### ISSUE THREAD

**Issue by Ingles-con-Kip** [godofredoninja/simply#93]
Posts marked for members or premium do not display most of the post excerpts in the home page loop, however some posts excerpts remain (even if all posts are marked for members only). 

Ideally, post excerpts would remain irrespective of membership.

**Comment by godofredoninja** [comment]
Hi @Ingles-con-Kip 

if you have a custom excerpt then it will be displayed. If you do not have a custom excerpt for members then it will not be displayed.

**So how to fix this.**

- Have a custom excerpt in every post for members.
- [Using public previews](https://ghost.org/help/public-previews/)

**Comment by Ingles-con-Kip** [comment]
Hi again, 

Thanks so much, this resolved the issue but raised a new one. It's true that you need to use public preview in order for the excerpt to display to the public when the post is marked for members. The "free public preview" divider, however, doesn't seem to work. Irrespectively of where it is placed in the post, readers can only read header and excerpt content. I tried it on the casper theme and it worked fine. 

Again, thank you so much for your help.

**Comment by godofredoninja** [comment]
Hi.

I knew you would ask me a related question. 😂 

Now here's a little problem. 

If I use the default, then the subscription info box will not be translated, because it comes by default from Ghost. And the Simply theme is multi-language, the idea is that when you change the language the whole page is translated. As I mentioned before this comes from Ghost and will always be in English. 

But for the next version I will leave it as it comes by default. Each user will take the one that suits him best.

**Comment by Ingles-con-Kip** [comment]
Okay. That works for me. Thanks for the help and the hard work.

**Comment by godofredoninja** [comment]
Hello.

Thanks for your help.

I have good news for you.

In the new version and brings by default the content preview.

d74060d4ef6a8f453454528c0fca64874da04934
